### ISSUE TITLE
关于在线调用貌似是不可以用raw,github.com

### ISSUE THREAD

**Issue by duguying** [shuiniuer/Niuer#2]
关于在线调用貌似是不可以用raw,github.com的，在IE下会有问题。因为mime并不是js……

**Comment by shuiniuer** [comment]
的确，之前没有注意。。。看看有没有更好的解决方式

**Comment by duguying** [comment]
@shuiniuer 要不你直接到BAE上建一个js库吧，只是每次都要上传了。

**Comment by duguying** [comment]
@shuiniuer 这个值得看一下http://rawgithub.com/

**Comment by duguying** [comment]
@shuiniuer 老大啊，你幸福了 :smile: 
解决这个问题很简单，只要把
https://raw.github.com/shuiniuer/Niuer/master/niuer.js
改为
https://rawgithub.com/shuiniuer/Niuer/master/niuer.js
就可以了 :smile: 
他的实现原理很简单，我们都能够想到：从raw.github读取然后添加mime
